### DISCUSSION TITLE
Vale linting on pull request

### DISCUSSION THREAD

**Discussion by pwalleni** [reviewdog/reviewdog#1317] [Q&A]
Hi!

I want to use Vale for checking the documentation quality of markdown files added or changed in a pull request. I trigger Vale with the following GitHub Actions workflow:

``` yaml
---
name: Check docs quality
on:
  pull_request_target:
    branches:
      - 'main'
      - 'master'
    paths:
      - 'docs/**/*.md'

jobs:
  vale:
    name: Vale Linter
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3.1.0
      - name: Run Vale cli
        uses: errata-ai/vale-action@reviewdog
        with:
          fail_on_error: true
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
```

The Vale settings file:
```
Packages = Microsoft
StylesPath = .vale/styles
Vocab = Ours
MinAlertLevel = suggestion
[*.md]
BasedOnStyles = Vale, Microsoft
```

The GitHub Actions job gets triggered as expected when a pull request is opened or updated with more commits, but the reviewdog filtering isn't behaving as expected. It doesn't fail the job and doesn't filter the results. I expect the job to fail and reviewdog to add decoration to the pull request only for the files that have been changed.
