### DISCUSSION TITLE
How to properly utilize SARIF files in Github Actions

### DISCUSSION THREAD

**Discussion by pragmaticivan** [reviewdog/reviewdog#1607] [Q&A]
```yml
- uses: reviewdog/action-setup@v1
  with:
    reviewdog_version: v0.15.0

- name: Run reviewdog
  env:
    REVIEWDOG_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  run: |
    echo -n "$(cat trivy-results.sarif)" | reviewdog -reporter=github-pr-review -f=sarif -level=info -diff="git diff FETCH_HEAD"

```

Unless I'm missing something, this command should have worked, but it produces nothing (not even logs) in GitHub actions. Am I missing something?
