### DISCUSSION TITLE
reviewdog: failed to get merge-base commit: exit status 128

### DISCUSSION THREAD

**Discussion by zawiszaty** [reviewdog/reviewdog#884] [Q&A]
:wave: I try to add reviewdog to pipeline in gitlabci but I have this error. 
```
//.reviewdog.yaml
runner:
  phpstan:
    format: phpstan
    cmd: php vendor/phpstan/phpstan/bin/phpstan analyse ./src --level 2
```
and I use this command to run `reviewdog -reporter=gitlab-mr-discussion`
and I have no idea why I have this error `reviewdog: failed to get merge-base commit: exit status 128`

**Comment by ArMourMag** [comment]
Hello, I have the same issue.

 ```bash
reviewdog -reporter=gitlab-mr-discussion
2021/03/15 10:24:07 reviewdog: [start]	runner=cppcheck
2021/03/15 10:24:07 reviewdog: [finish]	runner=cppcheck
reviewdog: failed to get merge-base commit: exit status 128
```

//.reviewdog.yaml
```yaml
runner:
    cppcheck:
        cmd: cppcheck --std=c++11 --std=c11 --std=posix --force --enable=all --template='{file}:{line} {message}' --project=compile_commands.json
        errorformat:
          - "%f:%l %m"
        level: warning
```
