### DISCUSSION TITLE
How to use reviewdog if linter doesn't not produce lint results in success cases

### DISCUSSION THREAD

**Discussion by Dwite** [reviewdog/reviewdog#931] [Q&A] [answered]
Hello, thank you for the great tool, we've are currently in the process of integrating it using GitHub Actions + Android ktlint

```
- name: Run reviewdog
        if: ${{ always() }}
        env:
          REVIEWDOG_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          cat ktlintMainSourceSetCheck.xml | \
            reviewdog -f=checkstyle -name="ktlint" -reporter=github-pr-review
```
`ktlintMainSourceSetCheck.xml` is a path to the lint result, but it's not created if there are no errors. This result produces following output

```
cat: ktlintMainSourceSetCheck.xml: No such file or directory
reviewdog: parse error: EOF
```

And my question is - what do you think is the best approach to resolve this?
1. Don't invoke the reviewDog in case there is no file using some logical checks in the step
2. Some custom reviewdog configuration that will not fail the build step in case of errors?
3. Prevent reviewdog step to failure the pipeline using `continue-on-error` 
4. Execute reviewdog step only in case of failure from previous steps (linting failed the pipeline)
5. Try to configure linter to always produce the file
6. ???
