### ISSUE TITLE
[Support] Avoiding 'this is not PullRequest build'

### ISSUE THREAD

**Issue by Kakadu** [reviewdog/reviewdog#1042]
I'm trying to hack environment to add lint to a pull request from [workflow](https://github.com/Kakadu/fp2021/runs/3477285589). I think that I set all required environment variables from Readme but reviewdog still complaints about 'this is not PullRequest build' Do you see anything obviously wrong?

```
Run cat lints.rdjsonl | reviewdog -f=rdjsonl -filter-mode nofilter -reporter=github-pr-review -guess
  cat lints.rdjsonl | reviewdog -f=rdjsonl -filter-mode nofilter -reporter=github-pr-review -guess
  shell: /usr/bin/bash -e {0}
  env:
    REVIEWDOG_TOKEN: ***
    LANG_NAME: Test
    PIARAST_NAME: Kakadu
    CI_PULL_REQUEST: 4
    CI_COMMIT: 398ad4c2b2386643421c9cef5695326b4f9f9b46
    CI_REPO_OWNER: Kakadu
    CI_REPO_NAME: fp2021
    REVIEWDOG_GITHUB_API_TOKEN: ***
reviewdog: this is not PullRequest build.

```
