### ISSUE TITLE
some messages unable send to gitlab mr discussion with giltab ci mr discussion reporter

### ISSUE THREAD

**Issue by bonniechen1119** [reviewdog/reviewdog#1048]
We use pylint to scan our code, and results unable send to gitlab mr discussion.
For example, our results are:
xxxxx.py:17:Trailing whitespace
xxxxx.py:27:Final newline missing
xxxxx.py:1:Module name "juan-test" doesn't conform to snake_case naming style
xxxxx.py:1:Missing module docstring
xxxxx.py:1:Unable to import 'gitlab'
xxxxx.py:6:Constant name "url" doesn't conform to UPPER_CASE naming style
xxxxx.py:7:Constant name "token" doesn't conform to UPPER_CASE naming style
check in gitlab mr ,unable see reviewdog comment in gitlab mr

**Comment by ljluestc** [comment]
```
stages:
  - lint

pylint:
  stage: lint
  image: python:3.9
  script:
    - pip install pylint pylint-gitlab
    - pylint --output-format=pylint_gitlab.GitlabCodeClimateReporter . > codeclimate.json
    - cat codeclimate.json | reviewdog -efm="%f:%l:%c: %m" -reporter=gitlab-mr-discussion -name="Pylint" -level=warning
  artifacts:
    paths:
      - codeclimate.json
  only:
    - merge_requests
```
