### ISSUE TITLE
Bitbucket pipeline: Reviewdog does not fail if the linter errors out

### ISSUE THREAD

**Issue by epleterte** [reviewdog/reviewdog#1070]
Hey,

following the instructions I added a section to my bitbucket pipeline (not quite settled on how I want to authenticate, so focus here is on the linting):

```
- step:
        name: Linting with Reviewdog
        image: golangci/golangci-lint:v1.31-alpine
        script:
          - git config --global url."git@bitbucket.org:myorg".insteadOf "https://bitbucket.org/myorg"
          - echo "${REPO_SECRET}" | base64 -d > ~/.ssh/id_ed25519 && chmod 0700 ~/.ssh/id_ed25519
          - apk add openssh
          - wget -O - -q https://raw.githubusercontent.com/reviewdog/reviewdog/master/install.sh | 
              sh -s -- -b $(go env GOPATH)/bin
          - golangci-lint run --out-format=line-number --new-from-rev=HEAD~1 ./... | reviewdog -f=golangci-lint -reporter=bitbucket-code-report -fail-on-error
 ```

I'm running this manually as well, just using `golangci-lint run --out-format=line-number ./`. My question/problem is this: If I run this, the linter can/will fail without reviewdog failing (even with "fail-on-error").
...and reviewdog is not failing because the linter isn't producing the expected output, I assume.
I get exit code 3 from one of my tests, golangci-lint complains about not being able to build:
`ERRO Running error: buildir: analysis skipped: errors in package: [...]`

Advice on dealing with this? I realize reviewdog hasn't gotten any errors to complain about, but I do expect everything to fail if the linter fails.

My current solution is to add a step before the linting action to achieve the expected behavior: `set -o pipefail`
Ex:

```
          - wget -O - -q https://raw.githubusercontent.com/reviewdog/reviewdog/master/install.sh | 
              sh -s -- -b $(go env GOPATH)/bin
          - set -o pipefail
          - golangci-lint run --out-format=line-number --new-from-rev=HEAD~1 ./... | reviewdog -f=golangci-lint -reporter=bitbucket-code-report -fail-on-error
```

Advice is welcome. I'd be happy to make a PR to update the example if this is an improved setup. Very open to input :)
Thanks!
