### ISSUE TITLE
filter findings behaves differently after push and after merge to master

### ISSUE THREAD

**Issue by yoavamirpayem** [reviewdog/reviewdog#1076]
Hi, i've set up review dog to run on my repo,
this is my configuration: 
```
name: reviewdog

on: [pull_request]

jobs:
  eslint:
    name: runner / eslint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - run: yarn install
      - uses: reviewdog/action-eslint@v1
        with:
          reporter: github-check
```

my checks are passing on PR, i have some warning but no errors, and all the warning go to filtered findings section, but when i merge the PR , all those warning move to 'findings' section and the test fails. is there any configuration the i'm missing here ?
