### ISSUE TITLE
ReviewDog PR reporter doesn't work when PR is draft

### ISSUE THREAD

**Issue by edmondo1984** [reviewdog/reviewdog#1094]
I am using reviewdog reporter via wemake-python-styleguide. When I choose the reporter 'github-pr-review'
with the following build

```
name: "lint"

on:
  push:
  pull_request:
    # The branches below must be a subset of the branches above
    branches: [ main ]
jobs:
  analyze:
    name: Analyze
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: wemake-python-styleguide
      uses: wemake-services/wemake-python-styleguide@0.15.3
      with:
        reporter: 'github-pr-review'
      env:
        GITHUB_TOKEN: ${{ secrets.github_token }}

```
but unfortunately it says: reviewdog: this is not PullRequest build.

However, it is a pull request build. Maybe it's because the pull request is DRAFT?
