### ISSUE TITLE
I would like to run reviewdog in github actions but not post comments. How do I achieve this?

### ISSUE THREAD

**Issue by programatologist** [reviewdog/reviewdog#1105]

**Comment by runspired** [comment]
Same. I'm trying to use the local reporter to achieve this, will post solution here if I come up with something.

**Comment by Wattyyy** [comment]
@programatologist 
Did you set the value of `reporter` to `github-pr-review`?
I ran into the same problem but solved it by changing the `reporter` value from `github-check` to `github-pr-review`.

```yml
jobs:
  eslint:
    name: eslint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "16.13"
      - run: npm install
      - uses: reviewdog/action-eslint@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          reporter: github-pr-review
```

**Comment by programatologist** [comment]
@runspired 
I got the solution
Add `fetch-depth: 0` in the checkout step. Following how the .yml looks like

```
name: reviewdog
on: [pull_request]
jobs:
  reviewdog:
    name: <>
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Setup Reviewdog
        uses: reviewdog/action-setup@v1
        with:
          reviewdog_version: latest
      - name: Run reviewdog
          run: reviewdog -diff="git diff origin/master" -fail-on-error=true
        ```

**Comment by runspired** [comment]
@programatologist similar to what I did (we use a checked in version of reviewdog/checkstyle in order to support local tooling better)

```yml
name: Backend CI
on:
  pull_request:

concurrency: 
  group: backend-${{ github.head_ref }}
  cancel-in-progress: true

jobs:
  checkstyle:
    name: checkstyle
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - run: git fetch origin master --depth=1
      - name: Checkstyle Diff
        run: yarn lint:api
```

the `lint:api` command is

```
cd ./backend-api && java -jar ./checkstyle-8.43-all.jar -c ./checkstyle.xml . -f xml | ./bin/reviewdog -f=checkstyle -name=checkstyle -fail-on-error=true -reporter=local -level=error -diff=\"git diff origin/master\"
```
