### ISSUE TITLE
Github check update failed

### ISSUE THREAD

**Issue by devindi** [reviewdog/reviewdog#1180]
Hi. I faced with an issue that reviewdog is not able to update github check using detekt report (https://detekt.dev/)

Detekt found around 700 issues in my project and reviewdog is not able to update check. 
reviewdog command: 
`reviewdog -f=checkstyle -name=detekt -reporter=github-pr-check   -level=error -filter-mode=file <detekt_report.xml` 
output: 
```
{"severity":"ERROR","time":"2022-05-19T12:23:25.004642822Z","logging.googleapis.com/sourceLocation":{"file":"/home/runner/work/reviewdog/reviewdog/doghouse/server/github_checker.go","line":"45","function":"github.com/reviewdog/reviewdog/doghouse/server.(*checkerGitHubClient).UpdateCheckRun"},"message":"UpdateCheckRun failed: {\"message\":\"Invalid request.\\n\\nOnly 65535 characters are allowed; 67901 were supplied.\",\"documentation_url\":\"https://docs.github.com/rest/reference/checks#update-a-check-run\"}"}```

Reviewdog version: 0.14.1

**Comment by carmanchris31** [comment]
This happens with any result that has too many messages.  Only 65535 characters are allowed in the request.

I believe I saw something about capping the request to avoid this somewhere in the ecosystem but can't remember where. It would be very helpful to avoid this error.

**Comment by Combustible** [comment]
I'm struggling with this same thing. I see there's a very similar issue in #1207 with more detail, which was closed by PR #1264, but somehow I'm still hitting this same problem. Possibly because I'm somehow not using the latest reviewdog, not sure.

**Comment by Combustible** [comment]
Oh, looks like that's simply because the last release was 9 months ago, and this was fixed 5 months ago. 

Unfortunately it looks like "Nightly" is also... 6+ months out of date, so also doesn't include the change....

Going to mess with how to build it directly myself I guess... but can we please get a new reviewdog release so we can have this change without clunky workarounds?

**Comment by Combustible** [comment]
Finally fiddle with this until it worked for me. 

For those looking for a GitHub actions workaround with minimal effort, I changed this code
```
    - name: Setup reviewdog
      uses: TeamMonumenta/reviewdog-action-setup@v1
      with:
        reviewdog_version: latest
```
to
```
    - name: Setup Golang / Reviewdog with cache
      uses: magnetikonline/action-golang-cache@v3
      with:
        go-version: ~1.18
    - run: go install github.com/reviewdog/reviewdog/cmd/reviewdog@master
```

Note my project doesn't have any golang stuff otherwise - if you already have golang set up you probably can use something simpler.
