### ISSUE TITLE
gofmt support

### ISSUE THREAD

**Issue by superstas** [reviewdog/reviewdog#128]
Hi there!

It'd be great if reviewdog supported gofmt.

My case: 

1) A not formatted file main.go
```go
$> cat main.go 
package main

import "fmt"

func main() { HelloWorld() }

func HelloWorld() {fmt.Println("hello world")}
```

2) reviewdog config
```yml
$> cat reviewdog.yml                                                                                                                                                                                            
runner:
  golint:
    cmd: golint $(go list ./... | grep -v /vendor/)
    errorformat:
      - "%f:%l:%c: %m"
  gofmt:
    cmd: gofmt -l -s .|xargs -I{} echo {}:1 file {} is not gofmted
    errorformat:
      - "%f:%l %m"
```

3) The diff:
```sh
$> git diff HEAD~1

diff --git a/main.go b/main.go
index fff5c2b..66228c0 100644
--- a/main.go
+++ b/main.go
@@ -2,4 +2,6 @@ package main
 
 import "fmt"
 
-func main() { fmt.Println("vim-go")}
+func main() { HelloWorld() }
+
+func HelloWorld() {fmt.Println("hello world")}
```
4) The result of execution:
```sh
$> reviewdog -diff='git diff HEAD~1'
main.go:7:1: [golint] exported function HelloWorld should have comment or be unexported
```
AFAIU that's because of "FilteredCheck.InDiff" that remains false during the "FilterCheck" [step](https://github.com/haya14busa/reviewdog/blob/master/filter.go#L20).

How would you fix it? 
I'd like to fix it myself and send PR if you don't mind. 

Thanks in advance
