### ISSUE TITLE
Tfsec- parse error: failed to unmarshal rdjson (DiagnosticResult): proto: syntax error (line 1:1): unexpected token

### ISSUE THREAD

**Issue by marcincuber** [reviewdog/reviewdog#1568]
Started seeing issues such as:

Running tfsec with reviewdog 🐶 ...
  parse error: Invalid numeric literal at line 3, column 0
  reviewdog: parse error: failed to unmarshal rdjson (DiagnosticResult): proto: syntax error (line 1:1): unexpected token

I am using following workflow:
```
tfsec:
    name: "Aqua tfsec"
    if: github.ref != 'refs/heads/main' && github.event_name == 'pull_request'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: tfsec
        id: tfsec
        uses: reviewdog/action-tfsec@master
        with:
          working_directory: aws
          tfsec_flags: "--concise-output"
          reporter: github-pr-review
          fail_on_error: true
          github_token: ${{ secrets.API_GITHUB_TOKEN }}
```

Can you advise if that is related to the latest 0.15 release of reviewdog and whether there is a fix to the error?

**Comment by shogo82148** [comment]
It is not an issue of reviewdog but tfsec.
see https://github.com/reviewdog/action-tfsec/issues/95 and https://github.com/aquasecurity/tfsec/pull/2099.

**Comment by skrings** [comment]
>  whether there is a fix to the error?

Pinning the tfsec version to `v1.28.1` worked for us.

```
        with:
          working_directory: aws
          tfsec_version: "v1.28.1"
          tfsec_flags: "--concise-output"
          reporter: github-pr-review
          fail_on_error: true
          github_token: ${{ secrets.API_GITHUB_TOKEN }}
```
