### ISSUE TITLE
Can I use XO with review dog?

### ISSUE THREAD

**Issue by tomerh2001** [reviewdog/reviewdog#1577]
Hey, I just stumled across this amazing repo and I am thinking about integrating it with the CI/CD of our 14+ repos, that would help a lot.

I am using [XO](https://github.com/xojs/xo) as my linter, and I'm wondering if Reviewdog supports it.

**Comment by dgholz** [comment]
@tomerh2001 XO is using the ESLint formatters under the hood, so you can use its SARIF formatter. Make an `.reviewdog.yml` like:
```
runner:
  xo:
    cmd: npx --no-install -c 'xo -f @microsoft/eslint-formatter-sarif'
    level: warning
    format: sarif
```
and a linting workflow in `.github/workflows/js-lint.yml` like:
```
name: Lint Javascript
on:
  - pull_request:

jobs:
  xo-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          cache: npm
          node-version-file: '.nvmrc'
      - uses: reviewdog/action-setup@v1
      - run: |
          reviewdog -reporter=github-pr-review -runners=xo --fail-on-error
```
And make sure you have `xo` & `@microsoft/eslint-formatter-sarif` listed as dependencies in your `package.json`

See https://github.com/actions/setup-node/blob/main/docs/advanced-usage.md#node-version-file if you want to pull your Node version from a different file.
