### ISSUE TITLE
'reviewdog: .git exist but is not a directory' in submodule

### ISSUE THREAD

**Issue by kdevkr** [reviewdog/reviewdog#1614]
```yml
name: PR Status Check

on:
  pull_request:
    branches:
      - main

jobs:
  eslint:
    name: eslint
    runs-on: ubuntu-latest # ubuntu-22.04

    strategy:
      matrix:
        node: [18]

    steps:
      ###########################################
      ## Checkout
      ###########################################
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          repository: kdevkr/platform
          token: ${{ secrets.PLATFORM_TOKEN }}
          ref: main
      - name: Checkout submodules
        run: |
          git submodule update --init monorepo
          cd monorepo/
          git checkout ${{ github.event.pull_request.head.sha }}

      - uses: pnpm/action-setup@v2
        with:
          version: 8
          run_install: false
          package_json_file: './monorepo/frontend/package.json'
      - name: Set up Node ${{ matrix.node }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{matrix.node}}
          cache: 'pnpm'
          cache-dependency-path: ./monorepo/frontend/pnpm-lock.yaml

      - uses: reviewdog/action-setup@v1
      - name: Run reviewdog
        env:
          REVIEWDOG_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          reviewdog -version
          cd monorepo/frontend
          pnpm install
          npx --no-install -c "eslint -f rdjson ./src/" | reviewdog -f=rdjson -reporter=github-pr-check
```

```sh
reviewdog: .git exist but is not a directory
```

I wonder why the above error occurs when using git-submodule.
