### ISSUE TITLE
reviewdog: GET https://api.github.com/repos/{org}/{repo}/pulls/{num}/comments?per_page=100: 403 Resource not accessible by integration []

### ISSUE THREAD

**Issue by prm-dan** [reviewdog/reviewdog#1810]
Multiple reviewdog actions are failing now.  I'm seeing this with `action-actionlint` and tflint.

I removed more sensitive parts. 
```
Run reviewdog/action-actionlint@afad3b6ab835e5611bda8c8193377e2d5c21413d
  with:
    reporter: github-pr-review
    fail_on_error: true
    github_token: ***
    tool_name: actionlint
    level: error
    filter_mode: file
/usr/bin/docker run --name ghcrioreviewdogactionactionlintv1510_ecf035 --label cca572 --workdir /github/workspace --rm -e "INPUT_REPORTER" -e "INPUT_FAIL_ON_ERROR" -e "INPUT_GITHUB_TOKEN" -e "INPUT_TOOL_NAME" -e "INPUT_LEVEL" -e "INPUT_FILTER_MODE" -e "INPUT_REVIEWDOG_FLAGS" -e "INPUT_ACTIONLINT_FLAGS" -e "HOME" -e "GITHUB_JOB" -e "GITHUB_REF" -e "GITHUB_SHA" -e "GITHUB_REPOSITORY" -e "GITHUB_REPOSITORY_OWNER" -e "GITHUB_REPOSITORY_OWNER_ID" -e "GITHUB_RUN_ID" -e "GITHUB_RUN_NUMBER" -e "GITHUB_RETENTION_DAYS" -e "GITHUB_RUN_ATTEMPT" -e "GITHUB_REPOSITORY_ID" -e "GITHUB_ACTOR_ID" -e "GITHUB_ACTOR" -e "GITHUB_TRIGGERING_ACTOR" -e "GITHUB_WORKFLOW" -e "GITHUB_HEAD_REF" -e "GITHUB_BASE_REF" -e "GITHUB_EVENT_NAME" -e "GITHUB_SERVER_URL" -e "GITHUB_API_URL" -e "GITHUB_GRAPHQL_URL" -e "GITHUB_REF_NAME" -e "GITHUB_REF_PROTECTED" -e "GITHUB_REF_TYPE" -e "GITHUB_WORKFLOW_REF" -e "GITHUB_WORKFLOW_SHA" -e "GITHUB_WORKSPACE" -e "GITHUB_ACTION" -e "GITHUB_EVENT_PATH" -e "GITHUB_ACTION_REPOSITORY" -e "GITHUB_ACTION_REF" -e "GITHUB_PATH" -e "GITHUB_ENV" -e "GITHUB_STEP_SUMMARY" -e "GITHUB_STATE" -e "GITHUB_OUTPUT" -e "RUNNER_OS" -e "RUNNER_ARCH" -e "RUNNER_NAME" -e "RUNNER_ENVIRONMENT" -e "RUNNER_TOOL_CACHE" -e "RUNNER_TEMP" -e "RUNNER_WORKSPACE" -e "ACTIONS_RUNTIME_URL" -e "ACTIONS_RUNTIME_TOKEN" -e "ACTIONS_CACHE_URL" -e "ACTIONS_RESULTS_URL" -e GITHUB_ACTIONS=true -e CI=true -v "/var/run/docker.sock":"/var/run/docker.sock" -v "/home/runner/work/_temp/_github_home":"/github/home" -v "/home/runner/work/_temp/_github_workflow":"/github/workflow" -v "/home/runner/work/_temp/_runner_file_commands":"/github/file_commands" -v "/home/runner/work/{repo}/{repo}":"/github/workspace" ghcr.io/reviewdog/action-actionlint:v1.51.0
reviewdog: GET https://api.github.com/repos/{org}/{repo}/pulls/{num}/comments?per_page=100: 403 Resource not accessible by integration []
```
