### ISSUE TITLE
Reviewdog posts and deletes GitHub review comments with multiple runners

### ISSUE THREAD

**Issue by pietrodn** [reviewdog/reviewdog#1911]
Hi! I am checking my codebase that is composed of an API module (written in Python) and a backoffice frontend (written in TypeScript).

My reviewdog config file is:

```yaml
runner:
  api-ruff-check:
    cmd: "cd api && poetry run ruff check -q --output-format=rdjson"
    format: rdjson
    level: error
    name: "ruff check (api)"

  backoffice-v2-lint:
    cmd: "cd backoffice-v2 && yarn run lint"
    format: eslint
    level: error
    name: "ESLint (backoffice-v2)"
```

I injected one linting error for each one of the linters to test the system.

On CircleCI I run the command:
```
./bin/reviewdog -reporter=github-pr-review -name=reviewdog -level=info
```

Locally:
```
reviewdog -guess -reporter=github-pr-review -log-level=debug
```

(I have set the GitHub token in the environment variable.)

I'm trying to run reviewdog locally but the same things happens on CircleCI:
- if only one of the two runners is enabled, a PR comment is correctly posted.
- **if both runners are enabled in the `.reviewdog.yml`, the two GitHub review comments appear momentarily and then disappear.** I can see them by leaving the PR page open, but as soon as I reload it they disappear...

This is really weird. When I see the comments, I see them as _different_ code review batches, while they should be inside the same. Is each runner posting its own review comments.

My hypothesis (unverified) is that each runner is seeing each other's comments and deleting them.

**Comment by pietrodn** [comment]
Note that the bug also happens with two identically configured ESLint's:

```yml
runner:
  backoffice-v2-lint:
    cmd: "cd backoffice-v2 && yarn run lint"
    format: eslint
    level: error
    name: "ESLint (backoffice-v2)"

  public-frontend-lint:
    cmd: "cd frontend-public && yarn run lint"
    format: eslint
    level: error
    name: "ESLint (frontend-public)"
```

If, instead, I collapse them, I see two comments in the same review block:

```yml
runner:
  backoffice-v2-lint:
    cmd: "(cd backoffice-v2 && yarn run lint); (cd frontend-public && yarn run lint)"
    format: eslint
    level: error
    name: "ESLint"
```
