### ISSUE TITLE
no filtered findings in reviewdog checks report as of v0.20.2

### ISSUE THREAD

**Issue by fbienz** [reviewdog/reviewdog#1935]
Since the last update, the checks report for `-reporter=github-pr-check` does not show any filtered findings.
I'm using `eslint` to generate a report in checkstyle format and pipe the result into reviewdog. 
Unfiltered positives are correctly reported and annotated.

Here is my configuration:
github action:
```yaml
name: PR

on:
  pull_request:
    branches: [  "main" ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
      - run: npm ci --no-audit

      - uses: reviewdog/action-setup@v1
        # with:
          # reviewdog_version: v0.20.1 # this version has the functioning checks report.
      - name: reviewdog npm lint
        run: npm run lint:ci | reviewdog -name=eslint -f=checkstyle -reporter=github-pr-check
        env:
          REVIEWDOG_GITHUB_API_TOKEN: ${{ secrets.github_token }}
```
package.json scripts:
```json
{
  "scripts": {
    "lint:ci": "eslint --ext .jsx,.js ./src -f checkstyle"
  },
}

```
