### ISSUE TITLE
not work in my private gitlab repo

### ISSUE THREAD

**Issue by FelixSeptem** [reviewdog/reviewdog#261]
I'am new to `reviewdog`,I config as below:
add file `.reviewdog.yml`
```yaml
# reviewdog.yml

runner:
  golangci:
    cmd: golangci-lint run --enable goimports --enable gocritic --skip-dirs ./vendor --out-format=line-number ./...
    errorformat:
      - '%E%f:%l:%c: %m'
      - '%E%f:%l: %m'
      - '%C%.%#'
    name: golangci
```

and add it into my `.gitlab-ci.yml` as below:
```yaml
reviewdog:
  stage: stats
  allow_failure: true
  variables:
    REVIEWDOG_GITLAB_API_TOKEN: "MYTOKEN"
    GITLAB_API: "https://mygitlab.com/api/v4"
    REVIEWDOG_INSECURE_SKIP_VERIFY: "true"
  before_script:
    - go install github.com/golangci/golangci-lint/cmd/golangci-lint
    - go get -u github.com/reviewdog/reviewdog/cmd/reviewdog
  script:
    - reviewdog -conf=.reviewdog.yml -reporter=gitlab-mr-discussion
```

the running result is:
```bash
$ reviewdog -conf=.reviewdog.yml -reporter=gitlab-mr-discussion
Job succeeded
```
nothing happened,even through I try to trigger it by add some lint error into my code.Anything I missed in my config?
