### ISSUE TITLE
Report on pushes to PR from GitHub Actions

### ISSUE THREAD

**Issue by mkorablin** [reviewdog/reviewdog#350]
I'm running into issue reporting on changes made to already opened PR running reviewdog via GitHub Actions.

Here's the step setup:
```yaml
- name: Lint
        env:
          REVIEWDOG_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: npm run lint:ci | reviewdog -f=checkstyle -name=eslint -reporter=github-check
```

What I get as a result is the following:
```bash
reviewdog: this is not PullRequest build.
```

I've also tried using `github-pr-check` which results in the same error and `github-check` which surprisingly results in:
```bash
reviewdog: unknown -reporter: github-check
```
even though this reporter seem to be present in the code:
https://github.com/reviewdog/reviewdog/blob/6608494d1b6757d4866b03a11df557d882c2feef/cmd/reviewdog/main.go#L208-L209

I would appreciate any help
