### ISSUE TITLE
Need Help with gitlab CI setup

### ISSUE THREAD

**Issue by aldefy** [reviewdog/reviewdog#469]
All i get is >>
`./bin/reviewdog -conf=./.reviewdog.yml -reporter=gitlab-mr-discussion`
``` sh
 2020/02/09 11:33:31 reviewdog: [start]	runner=lint
 2020/02/09 11:33:44 reviewdog: [finish]	runner=lint
```
Yml file :
```yml
runner:
  lint:
    cmd: ktlint --reporter=checkstyle
    format: checkstyle
    level: warning
    tee: true
```

Also, setup appropriate env variables in gitlab CI/CD settings 
But no changes/comments on the MR Discussion

**Comment by aldefy** [comment]
@haya14busa any help ?

**Comment by josephhaddad55** [comment]
Hey, @aldefy I'm experiencing a similar issue where reviewdog isn't posting a message on my GitLab MR, however, I was able to produce a helpful error message in my build logs when linting my Terraform example project below. Hopefully, my configuration can push you in the right direction. Let me know if you're able to get reviewdog to post a message on the MR. 

```shell
 $ tflint . | reviewdog -name="tflint-discussion" -tee -reporter="gitlab-mr-discussion"
 2020/02/26 02:03:50 reviewdog: [start]	runner=tflint
 1 issue(s) found:
 Error: "t2.micron" is an invalid value as instance_type (aws_instance_invalid_type)
   on instance.tf line 8:
    8:   instance_type        = "t2.micron"  
 2020/02/26 02:03:51 reviewdog: [finish]	runner=tflint
 ERROR: Job failed: exit code 1
```
[Link to the complete build log](https://gitlab.com/jhad789/infra/-/jobs/450142955)
[Link to project](https://gitlab.com/jhad789/infra/-/tree/reviewdog-pr-message)

```yaml
# .gitlab-ci.yml

image: ubuntu:18.04

stages:
  - lint

reviewdog-tflint:
  stage: 'lint'
  only:
   - branches
  except:
   - master
  # Install & Initialize Terraform & TfLint
  before_script:
    - apt-get -y update 
    - apt-get install -y git
    - apt-get install -y curl
    - apt-get install -y unzip
    - curl -LO https://raw.github.com/robertpeteuil/terraform-installer/master/terraform-install.sh
    - chmod +x terraform-install.sh
    - ./terraform-install.sh -a
    - terraform init
    - curl -sfL https://raw.githubusercontent.com/reviewdog/reviewdog/master/install.sh| sh -s -- -b /bin
    - curl -L "$(curl -Ls https://api.github.com/repos/terraform-linters/tflint/releases/latest | grep -o -E "https://.+?_linux_amd64.zip")" -o tflint.zip && unzip tflint.zip && rm tflint.zip && mv tflint /bin
  # Lint
  script:
    - export REVIEWDOG_GITLAB_API_TOKEN=$REVIEWDOG_GITLAB_API_TOKEN
    - tflint . | reviewdog -name="tflint-discussion" -tee -reporter="gitlab-mr-discussion"
    - tflint . | reviewdog -name="tflint-commit" -tee -reporter="gitlab-mr-commit"
```

```yaml
# .reviewdog.yml

runner: 
  tflint:
    cmd: tflint
    errorformat: 
      - "%f:%l:%c: %m"
    level: warning
```

**Comment by Miradorn** [comment]
@josephhaddad55 it seems to me your errorformat is wrong. The `tflint` output doesn`t have a very nice output format for reviewdog in it's standard config.
you could try using `tflint --format=checkstyle` and changing your `reviewdog.yaml` to `errorformat: ["checkstyle"]`, that should probably work (I'm not 100% sure that the `checkstyle` format inside `reviewdog.yaml` works, I only know that it can be used as a command line argument.)

**Comment by aldefy** [comment]
I will test thanks for the update

**Comment by josephhaddad55** [comment]
@Miradorn Thank you for pointing me in the right direction 🙏. I was able to generate an error message in my MR with `tflint`. I had to specify `-f checkstyle` in a few more spaces. 

```yml
# .gitlab-ci.yml
...
script: 
  - export REVIEWDOG_GITLAB_API_TOKEN=$REVIEWDOG_GITLAB_API_TOKEN
  - tflint -f checkstyle | reviewdog -f=checkstyle -name="tflint-discussion" -tee -reporter="gitlab-mr-discussion"
  - tflint -f checkstyle | reviewdog -f=checkstyle -name="tflint-commit" -tee -reporter="gitlab-mr-commit"

```

```yml
# .reviewdog.yml

runner:
   tflint:
     cmd: tflint --format=checkstyle
     errorformat: ["checkstyle"]
     level: warning

```

@aldefy For `ktlint` I recommend doing something similar and specifying `checkstyle` as the overall error format. This was the generated MR comment:  

<img width="979" alt="tflint-checkstyle" src="https://user-images.githubusercontent.com/33713907/75613126-075ac580-5af8-11ea-842d-974459aeb647.png">
