### ISSUE TITLE
Slow linting due to filtering being done after linters inspect the whole project

### ISSUE THREAD

**Issue by rjherrera** [reviewdog/reviewdog#474]
I am running reviewdog for 3 linters, rubocop, eslint and stylelint, but it is getting slower and slower as reviewdog receives the output piped from linters, and linters inspect all files. I do something like this in my CI job:
```bash
bundle exec rubocop . | ./bin/reviewdog -reporter=github-pr-review -f=rubocop
``` 
The thing is running `rubocop .` or `eslint .` is very slow in big projects, and seems inefficient to run linters over all files to _then_ have them filtered by reviewdog github-pr reporter.

I tried with something like this:
```bash
files=$(git diff origin/master --name-only)
bundle exec rubocop $(echo $files) | ./bin/reviewdog -reporter=github-pr-review -f=rubocop
```

Which works but doesn't seem to solve the whole problem as linters don't behave properly when handed filenames as input, for example eslint starts linting ruby files that came in the diff. Linters work well when given directories, like `.` but when given files they somehow force the linting, regardless of extensions and exclusions stated in their configuration files.

Do you have any ideas of how to address this? I don't think I am the first one with this issue, maybe you have insights. I also don't think it is an issue of reviewdog's code but rather a problem of reviewdog's philosophy, as it does the job after the reporter, and reactively filters files. I think maybe reviewdog could do the filtering before, proactively, making the linting process much more effective.

**Comment by rcb4t2** [comment]
Bump! We'd like to see this too. @rjherrera did you ever find an elegant solution?

**Comment by rjherrera** [comment]
Hi there @rcb4t2! I don't know if it's elegant enough hahah, but I did it in a couple of steps in my circle ci setup:

```yml
      - run:
          name: Get files to lint
          command: git diff origin/master --name-only --diff-filter=d > tmp/files_to_lint

      - run:
          name: Run rubocop
          shell: /bin/bash
          command: |
            cat tmp/files_to_lint | grep -E '.+\.(rb)$' | xargs bundle exec rubocop --force-exclusion \
            | ./bin/reviewdog -reporter=github-pr-review -f=rubocop

      - run:
          name: Run eslint
          shell: /bin/bash
          command: |
            cat tmp/files_to_lint | grep -E '.+\.(js|jsx|vue)$' | xargs yarn run eslint \
            | ./bin/reviewdog -reporter=github-pr-review -f=eslint
``` 

so basically I got the diff and then filtered by extension. I had to do some tweaking, with for example the `--force-exclusion` flag in rubocop, but it works.
