### ISSUE TITLE
Handle exit_codes properly 

### ISSUE THREAD

**Issue by GieForce** [reviewdog/reviewdog#596]
Hi folks, 

I'm currently spending some time debugging rubocop with with reviewdog. 
This tool works great but I'm facing some problems which are not picked up properly by reviewdog. 
Consider having the following configuration set: 

A shell executable is executed on my local machine if env is not set.
```sh
#!/bin/sh
set -e

if [ -z "${REVIEWDOG_GITHUB_API_TOKEN}" ];
then
  reviewdog -fail-on-error -filter-mode=nofilter
else
  reviewdog -reporter=github-check
fi
```
The Github Actions workflow

```yml
 - name: Run reviewdog
   env:
      REVIEWDOG_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
   run: lint.sh
```
The `.reviewdog.yml` file: 

```yml
runner:
  rubocop:
    cmd: bundle exec rubocop
```

The commands are both working fine! 
But apparently, when the exit_code of rubocop is something different than `exit_code=1` it's getting picked up as  `succeeded` by reviewdog.
Is there a way to define on which `exit_codes` to fail? Maybe you can add some kind of logic to always fail except on `exit_code=0`? 

Things I tried to show the problem:

1. Consciously interrupt rubocop giving `exit_code=2` => `SUCCEED`
2. Apply wrong configuration in rubocop giving `exit_code=127` => `SUCCEED`
3. Mistype command in `.reviewdog.yml` giving `exit_code=?` => `SUCCEED`
