### ISSUE TITLE
Exit Code Confusion

### ISSUE THREAD

**Issue by mikebronner** [reviewdog/reviewdog#807]
Hi everyone,

I am currently stuck on version 0.9.17 because I am unable to get ReviewDog to work with the following external linters:
- PHPStan
- PHPCodeSniffer

They both return exit codes other than 0 when the command returns lint results. When I try to pass the data on to ReviewDog, it spits out the following error:

```sh
reviewdog: phpstan failed with zero findings: The command itself failed (exit status 1) or reviewdog cannot parse the results
```

I'm fairly certain that it's something I'm doing wrong in configuring reviewdog. Here is my config file and reviewdog command I'm running:

**.reviewdog.yml**
```yml
runner:
  phpcs:
    cmd: php phpcs.phar --ignore=vendor --standard=./phpcs.xml --extensions=php --report=checkstyle -q .
    errorformat:
      - checkstyle
    level: warning
  phpmd:
    cmd: php phpmd.phar . text ./phpmd.xml --ignore-violations-on-exit --suffixes=php | sed -r "s/([0-9]+)\s+/\1:/gI"
    errorformat:
      - phpstan
    level: warning
  phpstan:
    cmd: php phpstan.phar analyse --no-interaction --no-progress --level=max --memory-limit 1G --error-format=raw app bootstrap config database resources routes
    errorformat:
      - phpstan
    level: warning
```

**command**
```
reviewdog -diff="git diff develop" -runners=phpstan --fail-on-error=true
```

**Comment by haya14busa** [comment]
The error message is saying phpstan failed with exit status 1 even though it doesn't return anything (zero finding), which is weird and reviewdog treat it as a failure.

**Comment by mikebronner** [comment]
Hi @haya14busa, thanks for the quick response. Here's what's happening:
- PHPStan is return exit code 1 because it found issues in the code.
- I'm assuming ReviewDog is saying `zero finding` because none of the findings applied to changes in the current PR.

My expectations would be that if PHPStan has an exit code 1 (because it find issues elsewhere in the project) but ReviewDog filters those out, it would then indicate success, instead of failing. Does it make sense how I explained it?

**Comment by haya14busa** [comment]
> I'm assuming ReviewDog is saying zero findings because none of the findings applied to changes in the current PR.

This is wrong. It sees all findings in this case.
One possible problem is reviewdog failed to parse some results.
You can use `-filter-mode=nofilter` and/or `-tee` to debug the issue.

**Comment by Gregory-Berkman-Imprivata** [comment]
I am running into this issue and was wondering if there has been any update. 

Here is my `reviewdog.yaml` file: 
```
---
runner:
  yamllint:
    cmd: docker run --rm -it -v $(pwd):/data cytopia/yamllint --format "parsable" -c ./config/.yamllint.yaml .
    errorformat:
      - "%f:%l:%c: %m"
    name: yamllint
    level: error
    filter-mode: nofilter
```

and when I run I get this: 
```
$+ reviewdog -conf="./.reviewdog.yml" -diff="git diff"
2020/12/14 17:16:29 reviewdog: [start]	runner=yamllint
2020/12/14 17:16:29 reviewdog: [finish]	runner=yamllint	error=exit status 1
reviewdog: yamllint failed with zero findings: The command itself failed (exit status 1) or reviewdog cannot parse the results
```
I think the command itself is failing and I think it has to do with directory scope. For example I think `$(pwd)` or even `.` may point to a different directory when being run in reviewdog vs when being run in the base directory in the shell (where it runs fine and gives expected results).
