### ISSUE TITLE
reviewdog: this is not PullRequest build

### ISSUE THREAD

**Issue by Yuhta28** [reviewdog/reviewdog#889]
*Details are in this Stack Overflow*
(https://stackoverflow.com/questions/66309574/reviewdog-this-is-not-pullrequest-build)

 I would like to be able run reviewdog on CircleCI, and when I did git push, it will check the documentation for text errors, and reviewdog will send out a pull-request if there is an error.

```yml:
- run: # (d1)
          name: "Execute textlint for README.md"
          command: npx textlint --rule common-misspellings README.md >> .textlint.log
      - run: # (d2)
          name: "Execute reviewdog"
          when: on_fail
          command: |
            cat .textlint.log | ./bin/reviewdog -f=checkstyle -name="textlint" -reporter="github-pr-review"
```

Before I `git push`, I set Environment Variables, REVIEWDOG_GITHUB_API_TOKEN and turned on the checkbox, **Only build pull requests**

After that, I `git push` and job, `Execute reviewdog` said

```
#!/bin/bash -eo pipefail
cat .textlint.log | ./bin/reviewdog -f=checkstyle -name="textlint" -reporter="github-pr-review"
reviewdog: this is not PullRequest build.
CircleCI received exit code 0
```

I would appreciate any help

**Comment by haya14busa** [comment]
https://github.com/reviewdog/reviewdog/issues/872#issuecomment-775898312

**Comment by Yuhta28** [comment]
@haya14busa 
Before I `git push`, I set Env Variables, **REVIEWDOG_GITHUB_API_TOKEN** in CircleCI Project Settings.
Does that mean it's not enough?

**Comment by haya14busa** [comment]
I meant circle CI's PR related env vars such as CIRCLE_PR_NUMBER

**Comment by Yuhta28** [comment]
@haya14busa 
I found CIRCLE_PR_NUMBER is in empty.
I think that this Env Variable is need to be set something number; however,  I have no idea how to do that.
How can I do this?

```
#!/bin/bash -eo pipefail
echo $CIRCLE_PR_NUMBER

CircleCI received exit code 0
```

**Comment by Yuhta28** [comment]
I was wrong about something.
I thought reviewdog  would automatically issue PR, but it was mistake, wasn't it?
reviewdog just added comment to the PR which people issue.
At first, I `git push` on master branch.

1. I issue PR on another branch.
2. CircleCI runs jobs as another branch.
![Screenshot 2021-02-27 10:29:44](https://user-images.githubusercontent.com/54278643/109372589-9ce88b00-78ed-11eb-9d83-ca2965bd8b6b.png)
3. However, reviewdog happened `parse error`

I guess there is error why `CIRCLE_PR_NUMBER` is empty, and I'm going to investigate it.

**Comment by rpbaltazar** [comment]
I'm facing a similar issue with github actions.
```
  rubocop:
    name: Run Rubocop
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Read ruby version
        run: echo ::set-output name=RUBY_VERSION::$(cat .ruby-version | cut -f 1,2 -d .)
        id: rv
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: "${{ steps.rv.outputs.RUBY_VERSION }}"
      - uses: reviewdog/action-rubocop@v1
        env:
          REVIEWDOG_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          rubocop_version: gemfile
          rubocop_extensions: rubocop-rails:gemfile rubocop-rspec:gemfile rubocop-performance:gemfile
          github_token: ${{ secrets.github_token }}
```

and i always get the message `reviewdog: this is not PullRequest build`

**Comment by Yuhta28** [comment]
> 
> 1. I issue PR on another branch.
> 2. CircleCI runs jobs as another branch.
>    ![Screenshot 2021-02-27 10:29:44](https://user-images.githubusercontent.com/54278643/109372589-9ce88b00-78ed-11eb-9d83-ca2965bd8b6b.png)
> 3. However, reviewdog happened `parse error`
> 
> I guess there is error why `CIRCLE_PR_NUMBER` is empty, and I'm going to investigate it.


I resolved this issue.
I was wrong about the code here.
`npx textlint --rule common-misspellings README.md`

I need to add `-f checkstyle`.
So, I fix this code and issue PR on another branch.
`npx textlint -f checkstyle  README.md >> .textlint.log`


Finally, reviewdog worked, made a comment on PR.
![Screenshot at 2021-03-14 22-36-06](https://user-images.githubusercontent.com/54278643/111071926-c293a800-851b-11eb-8047-a3dc0e19574b.png)

**Comment by cep21** [comment]
@rpbaltazar did you ever solve your problem?  Same issue for me

**Comment by yuiseki** [comment]
same here...

[![Image from Gyazo](https://i.gyazo.com/541181ef0adc7854107d025ea7267c5c.png)](https://gyazo.com/541181ef0adc7854107d025ea7267c5c)

**Comment by rpbaltazar** [comment]
> @rpbaltazar did you ever solve your problem? Same issue for me

I don't think I've fixed the issue entirely, but setting the github action to run on pull_request seems to run the action which was good enough for me to start looking at something.

E.g created a `.github/workflows/reviewdog.yaml`

```
name: reviewdog
on: [pull_request]
jobs:
  brakeman:
    name: runner / brakeman
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2
      - name: brakeman
        uses: reviewdog/action-brakeman@v1
        with:
          github_token: ${{ secrets.github_token }}
          reporter: github-pr-review # Default is github-pr-check

  rubocop:
    name: runner / rubocop
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2
      - name: Read ruby version
        run: echo ::set-output name=RUBY_VERSION::$(cat .ruby-version | cut -f 1,2 -d .)
        id: rv
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: "${{ steps.rv.outputs.RUBY_VERSION }}"
      - uses: reviewdog/action-rubocop@v1
        with:
          rubocop_version: gemfile
          rubocop_extensions: rubocop-rails:gemfile rubocop-rspec:gemfile rubocop-performance:gemfile
          github_token: ${{ secrets.github_token }}
```
