### ISSUE TITLE
Multi Module Projects

### ISSUE THREAD

**Issue by roxspring** [reviewdog/reviewdog#898]
Hi

Just discovered ReviewDog and it looks very promising!

I'm working on a multi-module Maven project, where various static analysis plugins are configured to produce reports per-module. It appears that the right way of processing this in ReviewDog is something along the following lines, which is going to be pretty boring to maintain for 30+ modules:

```yaml
runner:
  module1-checkstyle:
    cmd: cat module1/target/checkstyleXml.xml
    format: checkstyle
  module2-checkstyle:
    cmd: cat module2/target/checkstyleXml.xml
    format: checkstyle
```

Is there a built in way to somehow process `**/target/checkstyleXml.xml` from a single runner?

Alternative, I presume that current best practice would be to process per-module reports into a single per-project report and pass that merged result into ReviewDog?
