### ISSUE TITLE
ERROR:  While executing gem ... (Gem::FilePermissionError)

### ISSUE THREAD

**Issue by recurator** [reviewdog/reviewdog#899]
Hello, 

We have used fully functional Github Action related to reek, rubocop, and brakeman and suddenly last week our action started to report errors.

GitHub Action Workflow file:

```
name: Code quality

on: [push]

jobs:
  code_quality:
    name: runner/code quality
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: runner/reek
      if: ${{ always() }}
      uses: reviewdog/action-reek@v1
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        reporter: github-check
        level: error
        fail_on_error: true

    - name: runner/rubocop
      if: ${{ always() }}
      uses: reviewdog/action-rubocop@v1
      with:
        rubocop_version: 0.89.1
        rubocop_extensions: rubocop-rails:2.7.1 rubocop-performance:1.7.1 rubocop-rspec:1.43.1
        github_token: ${{ secrets.GITHUB_TOKEN }}
        reporter: github-check
        level: error
        fail_on_error: true

    - name: runner/brakeman
      if: ${{ always() }}
      uses: reviewdog/action-brakeman@v1
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        reporter: github-check
        level: error
        fail_on_error: true
```

Reported errors:
```
Installing reviewdog ... https://github.com/reviewdog/reviewdog
  reviewdog/reviewdog info checking GitHub for tag 'v0.11.0'
  reviewdog/reviewdog info found version: 0.11.0 for v0.11.0/Linux/x86_64
  reviewdog/reviewdog info installed /tmp/tmp.EwUKZGaAeV/reviewdog
 Installing reek ... https://github.com/troessner/reek
  ERROR:  While executing gem ... (Gem::FilePermissionError)
      You don't have write permissions for the /var/lib/gems/2.7.0 directory.
```

```
Installing reviewdog ... https://github.com/reviewdog/reviewdog
  reviewdog/reviewdog info checking GitHub for tag 'v0.11.0'
  reviewdog/reviewdog info found version: 0.11.0 for v0.11.0/Linux/x86_64
  reviewdog/reviewdog info installed /tmp/tmp.A5rM4TLp6W/reviewdog
 Installing rubocop with extensions ... https://github.com/rubocop/rubocop
  ERROR:  While executing gem ... (Gem::FilePermissionError)
      You don't have write permissions for the /var/lib/gems/2.7.0 directory.
```
