### ISSUE TITLE
Reviewdog does not cause action step to fail

### ISSUE THREAD

**Issue by mrousavy** [reviewdog/reviewdog#907]
I'm running this step in a GitHub action:

```yml
    - name: Run TypeScript
      run: yarn typescript | reviewdog -f=tsc -reporter=github-pr-review -fail-on-error=true
      env:
        REVIEWDOG_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
```

for testing purposes, I added a tsc error.

![Screenshot 2021-03-12 at 12 38 12](https://user-images.githubusercontent.com/15199031/110935519-cfec3f00-832f-11eb-8c0d-3a9b0a330de0.png)

however, reviewdog still doesn't exit with an error, causing the action to report a "successful run" even though it obviously should've failed:

![Screenshot 2021-03-12 at 12 37 02](https://user-images.githubusercontent.com/15199031/110935536-d5e22000-832f-11eb-9d80-efcc3338c476.png)

Am I missing something? Full action is [here](https://github.com/cuvent/react-native-vision-camera/blob/main/.github/workflows/validate-js.yml)

**Comment by mrousavy** [comment]
Since the official "tsc" reporter didn't seem correct, I tried to use a custom efm:

```
yarn typescript | reviewdog -efm="%f:%l:%c - error TS%n: %m" -reporter=github-check -filter-mode=nofilter -fail-on-error
```

where `yarn typescript` is just `tsc --noEmit`

but this also did not work. It fails with exit code 2, but reviewdog just swallows that and does not fail the pipeline

**Comment by OldhamMade** [comment]
I'm finding similar issues with a different input. `-fail-on-error` does report some things failed, but the GitHub Action passes successfully.

Here's the config:

```yaml
runner:
  credo:
    name: credo
    cmd: mix credo suggest -a --strict --format=flycheck
    errorformat:
      - "%f:%l:%c: %t: %m"
      - "%f:%l: %t: %m"
    level: warning
    fail_on_error: true
  sobelow:
    name: sobelow
    cmd: mix sobelow --flycheck -i Config.CSP --exit
    errorformat:
      - "%f:%l:%c: %m"
      - "%f:%l: %m"
    level: warning
    fail_on_error: true

```

The action:

```yaml
      - name: "[ReviewDog] Check"
        env:
          REVIEWDOG_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          reviewdog -reporter=github-check -fail-on-error
          EXIT_CODE=$?
          echo "exit code: ${EXIT_CODE}"
          exit ${EXIT_CODE}
```

And the output:

```
2021/05/28 07:27:30 reviewdog: [finish]	runner=credo	error=exit status 4
2021/05/28 07:27:30 reviewdog: [finish]	runner=sobelow	error=exit status 1
2021/05/28 07:27:31 [sobelow] reported: https://github.com/ORG/PROJ/runs/NUM (conclusion=neutral)
2021/05/28 07:27:31 [credo] reported: https://github.com/ORG/PROJ/runs/NUM (conclusion=neutral)
exit code: 0
```

Maybe my action is wrong, but I've tried a number of variations and still get the same result: `exit 0`
