### ISSUE TITLE
PullRequest needs 'git' command: failed to run 'git rev-parse --show-prefix': exit status 128

### ISSUE THREAD

**Issue by yamin-oanda** [reviewdog/reviewdog#920]
Getting the above error when trying to run reviewdog in a CircleCI pipeline. Relevant part of pipeline:

```yaml
      - run:
          command: "curl -sfL https://raw.githubusercontent.com/reviewdog/reviewdog/master/install.sh| sh -s -- -b ./bin"
          name: Get Reviewdog
      - run:
          command: "sbt clean compile 2>&1 | ./bin/reviewdog -f=sbt -reporter=github-pr-review -diff='git diff main'"
          name: Reviewdog check
```

Tracing this back to the code, error seems to come from: https://github.com/reviewdog/reviewdog/blob/v0.11.0/service/github/github.go#L54

Which is calling: https://github.com/reviewdog/reviewdog/blob/v0.11.0/service/serviceutil/serviceutil.go#L10

Specifically, the code:

```go
        b, err := exec.Command("git", "rev-parse", "--show-prefix").Output()
	if err != nil {
		return "", fmt.Errorf("failed to run 'git rev-parse --show-prefix': %w", err)
	}
```

So this `err` seems to be `exit status 128`, which, according to TLDP, means 'an invalid exit code was passed to the exit command'. E.g., `exit 3.14`.

If it helps, I verified that the container I'm using (`hseeberger/scala-sbt:8u265_1.4.3_2.13.4`) does have git installed.

**Comment by seh** [comment]
This is most likely due to having started this GitHub Action step before having checked out the code in a preceding step.

**Comment by yamin-oanda** [comment]
This is a CircleCI build, and a bit more context:

```yaml
jobs:
  pr:
    docker:
      - image: hseeberger/scala-sbt:8u265_1.4.3_2.13.4
    steps:
      - checkout
      - restore_cache:
          key: sbt-cache
      - run:
          command: "curl -sfL https://raw.githubusercontent.com/reviewdog/reviewdog/master/install.sh| sh -s -- -b ./bin"
          name: Get Reviewdog
      - run:
          command: "sbt clean compile 2>&1 | ./bin/reviewdog -f=sbt -reporter=github-pr-review -diff='git diff main'"
          name: Reviewdog check
...
```

As shown above, git checkout was done before running reviewdog.
