### ISSUE TITLE
GitHub Action fails with "reviewdog: fail to open config: .reviewdog.yml not found"

### ISSUE THREAD

**Issue by seh** [reviewdog/reviewdog#923]
Following [the documentation's example](https://github.com/reviewdog/reviewdog/tree/ec704660d0a32c1794cf07a29f577347ebf99f6a#github-actions) of running Reviewdog for _golint_ and _go vet_ in "github-check" mode, I run into the following complaint:
```
reviewdog: fail to open config: .reviewdog.yml not found
```
This comes after running the following GitHub Actions steps:
```
- name: Set up Reviewdog
  uses: reviewdog/action-setup@v1
  with:
    reviewdog_version: latest
- name: Ensure Go files satisfy "golint" and "go vet"
  continue-on-error: true
  env:
    REVIEWDOG_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  run: |
    reviewdog -runners=golint,govet -reporter=github-check
```
It occurs to me now that perhaps there is no default _.reviewdog.yml_ file supplied with the _reviewdog/action-setup_ action, and that for lack of that file, there are no runners defined.

Are these examples all assuming that the user created a _.reviewdog.yml_ file like [the one shown here](https://github.com/reviewdog/reviewdog/tree/ec704660d0a32c1794cf07a29f577347ebf99f6a#reviewdog-config-file)?

**Comment by shogo82148** [comment]
`.reviewdog.yml` is optional, you don't need it.
Can you show me whole of your GitHub Actions workflow YAML file?

**Comment by seh** [comment]
Here's what I have so far, with some following jobs cut out that aren't pertinent for this inquiry. Note that here I'm showing what I attempted when I couldn't get the `-runners` flag as shown in [my original message above](https://github.com/reviewdog/reviewdog/issues/923#issue-858206615) to work.

<details>
<summary><i>.github/workflows/ci.yaml</i></summary>

```yaml
name: Continuous Integration
on:
- push
- pull_request
jobs:
  source-inspection:
    runs-on: ubuntu-latest
    steps:
    - name: Check out VCS repository
      uses: actions/checkout@v2
    - name: Set up Reviewdog
      uses: reviewdog/action-setup@v1
      with:
        reviewdog_version: latest
    - name: Ensure Go files satisfy "staticcheck"
      uses: reviewdog/action-staticcheck@v1
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        reporter: github-check
        #filter_mode: nofilter
        fail_on_error: true
    - name: Set up Go toolchain
      uses: actions/setup-go@v2
      with:
        go-version: 1.16
    - name: Ensure Go files satisfy "go vet"
      env:
        REVIEWDOG_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        go vet ./... | \
          reviewdog -f=govet -reporter=github-check -fail-on-error=true
    - name: Install extra Go tools
      run: go get golang.org/x/lint/golint
    - name: Ensure Go files satisfy "golint"
      env:
        REVIEWDOG_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        golint ./... | \
          reviewdog -f=golint -reporter=github-check -fail-on-error=true
    - name: Confirm Go source code is formatted per "gofmt"
      env:
        REVIEWDOG_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        gofmt -s -d . | \
          reviewdog -name="gofmt" -f=diff -f.diff.strip=0 -reporter=github-check -fail-on-error=true
```
</details>
